### ISSUE TITLE
Wake / foam artifacts when moving the camera quickly

### ISSUE THREAD

**Issue by Revmatek** [wave-harmonic/crest#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Have you checked the documentation to resolve your problem?

- [X] I have read the linked documentation and could not resolve my issue.

### Current Behavior

Rotating a camera quickly with visible foam / wakes can cause artifacts to appear. 

Artifact stretching out in a random direction 
<img width="718" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/4c215e42-4930-40e0-87bc-0dc16f7be293">
Artifacts stretching out from their source
<img width="628" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/de81a905-3fe8-4307-b100-a25ed547ff3e">
More defined artifact stretching out in a random direction
<img width="1604" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/f6c31406-a4a6-4e74-979f-579e62f35f6b">

### Expected Behavior

The wake / foam should remain rendered in the location it originally appeared and new foam streaks should not appear at random in whichever direction the camera rotation begins to halt.

### Steps To Reproduce

I was originally not able to reproduce this but I got a lucky glance I think at some artifacts in the "BoatWakes" scene, I will try to capture them.

1. Load the "BoatWake" scene
2. Hit play
3. Follow one of the smaller spheres near the edge with the camera looking down-ish and rotate the camera repeatedly until line based artifacts become apparent (this may take several attempts).

Seems a lot harder to do in the "BoatWake" scene for whatever reason. I am having difficultly getting it to happen again... ok following up more it is a lot easier to see if you make the ocean inputs flat and set all the Spectrum inputs to 0, you have to kinda aggressively use the mouse and WASD + Shift while rotating as if you where pivoting an object.

Here are some good example (I had to record to capture these) the video is a bit too big to upload (and it is mainly me spastically moving the camera). Some of these may be hard to see or distinguish. 

<img width="583" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/08588088-0115-42be-afde-fde7afc30b1c">
<img width="149" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/cc50d9bb-4bb9-4dd3-a8d7-bb641efdd0b7">
<img width="876" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/28bc08b5-7785-4383-946c-653bd98eb3b3">
<img width="1407" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/ea97501f-3d79-42a8-aaee-dcadeb94a862">
<img width="980" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/39f5161f-4720-44e6-b1c9-5940e09a8b0a">
<img width="1605" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/4347da0c-b8e4-4238-a84d-57ffe0fd194a">
<img width="1809" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/9144fb96-7986-44ad-9c4c-5dfaab2716fb">

In my earlier examples I have a physics object moving at high speeds that is generating a custom wake of sorts, but this happens with the default Sphere interaction if I manually attach one to the moving physics object. Generally this happens when looking at the boat from behind and then causually but quickly rotating the camera to view the boat from the front, the camera focuses on the vessel in general and rotates around it as its pivot. The cameras movement updates in LateUpdate, but changing this to Update has no effect.

Definitely caused by SphereInteractions, not any foam overrides.

### Unity Version

2021.3.26f1

### Crest Version

5.17.3

### Render Pipeline

Built-In

### Editor or Standalone

Editor (Edit Mode), Editor (Play Mode), Standalone

### Environment

```markdown
- OS: Windows
```

### Anything else?

I updated from 4.15.2 to 4.17.3 and this is one of the only outstanding issues that remained from what I was hoping would be fixed. I spent a lot of time trying various update methods to get this to not display artifacts hoping that there was some config I was not aware off. 

I can only assume the following:

- This is some sort of edge case / bug
- I am missing some configuration in my OceanRenderer that I am not aware of

**Comment by daleeidd** [comment]
Thanks. I was able to reproduce the issue. It is related to camera movement and not rotation. You need to move back and forth at an angle. The artefact is directional so depending on angle will determine the nature of it. Likely an artefact at the LOD transition. I will look into it.

**Comment by daleeidd** [comment]
Fixed for next release. This was streaking due to clamped texture sampling. The previous anti-streaking measure was not effective enough so implemented something more solid.

**Comment by Revmatek** [comment]
@daleeidd 

I patched from the commit that fixed this and played around with it for a while, it seems to have fixed the initial streaking problem. I am noticing some very similar streaking when zooming in and / out when rotating the camera as the LODs change. I am not positive it is from this change or if it is the same problem but it is worth looking at.  If you want me to make a new issue for this that is fine.

Its very easy to see in latest if you set the Wake10m size to max (40) and move the camera out of the WakeRig and increase the speed, then zoom in and out to the point where the foam is not visible

For reference:
![image](https://github.com/wave-harmonic/crest/assets/114962753/b631f6c7-ad94-44fc-ab99-0577469d5595)

Streaking in latest:
![image](https://github.com/wave-harmonic/crest/assets/114962753/6bf38d0c-469f-497d-88aa-44c7d294785e)
![image](https://github.com/wave-harmonic/crest/assets/114962753/d29b40e7-b7d6-40f8-9bff-919e2d04f360)
![image](https://github.com/wave-harmonic/crest/assets/114962753/e6fe94c5-bec5-477c-8bfd-9a0d9a8961e7)
![image](https://github.com/wave-harmonic/crest/assets/114962753/1d8523b0-55e9-4394-a283-aabc3c68e12a)

Seen in game when zooming in and out while moving the camera:
![image](https://github.com/wave-harmonic/crest/assets/114962753/90a54d9f-a62c-4b84-b73a-b0b76830c170)

It seems like as the wakes generate they start to form streaks near the edges of the tiles. Once this starts to happen you can zoom in and out or move the camera in general and it will start to magnify the issue:
![image](https://github.com/wave-harmonic/crest/assets/114962753/9a007cee-ad39-445d-b4de-af6ced782d43)

Seems to happen whenever foam appears and changes when the camera moves in various ways (spinning boat in circles here to create foam constantly):

![image](https://github.com/wave-harmonic/crest/assets/114962753/6c047c33-10cf-4eeb-bb1f-ce459709fc68)
![image](https://github.com/wave-harmonic/crest/assets/114962753/702f1c70-c208-42c5-9e59-9029b8c338ef)

**Comment by daleeidd** [comment]
Thanks. Looks like it is a problem with Dynamic Waves rather than foam. I struggled to reproduce it. But I have a potential fix if you're willing to test it? [fix-dynamic-waves-edge-artefacts](https://github.com/wave-harmonic/crest/tree/fix-dynamic-waves-edge-artefacts)

**Comment by Revmatek** [comment]
> Thanks. Looks like it is a problem with Dynamic Waves rather than foam. I struggled to reproduce it. But I have a potential fix if you're willing to test it? [fix-dynamic-waves-edge-artefacts](https://github.com/wave-harmonic/crest/tree/fix-dynamic-waves-edge-artefacts)

Yes, I will take a look shortly.

**Comment by Revmatek** [comment]
> > Thanks. Looks like it is a problem with Dynamic Waves rather than foam. I struggled to reproduce it. But I have a potential fix if you're willing to test it? [fix-dynamic-waves-edge-artefacts](https://github.com/wave-harmonic/crest/tree/fix-dynamic-waves-edge-artefacts)
> 
> Yes, I will take a look shortly.

I do still see the problem with these changes:
<img width="551" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/3e03728f-aa5f-4cea-9f94-ad35c41a9d62">

I am able to reproduce this in latest with the following steps:

1. Open "BoatWakes" scene
2. Set the "Foam Fade Rate" to 0 on the ocean renderer
3. Move the DemoCamera to the root of the scene so that it is no longer moving with the WakeRig
4. Zoom out:
<img width="609" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/2f13eaea-f066-4231-b9a9-98e222c962c1">

5. Zoom in to random portions of the wake 
<img width="631" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/d263e29d-69a0-4792-9438-6d9dd92f0955">

6. Repeat 4-5 and move / rotated the camera until you start to see corner like wakes appearing
7. Once you see the corner like wake, zoom in and out on it very slightly close up to see the corner become more defined / streaked 
<img width="649" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/d5bf9383-0d52-4d50-80ea-4ee5d66fc1e0">
<img width="847" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/fd38e3f3-d618-4209-bc60-42138413f752">

Stats if helpful:
<img width="239" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/b049a03f-2030-4b59-8e11-9d42e7960b15">

This last one I tried with the patch on latest just to make sure: 
<img width="725" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/7502f1c1-e2b6-4f25-a20d-21aebea223b3">

**Comment by Revmatek** [comment]
Here are some video steps, hard to describe.

https://github.com/wave-harmonic/crest/assets/114962753/75f55752-4df1-4f5e-a91d-145bdd18e51f

It seems easier to see with the wave spectrum zeroed out:
<img width="430" alt="image" src="https://github.com/wave-harmonic/crest/assets/114962753/c71eb678-fc5f-4c35-90ee-55262ed68e4f">

https://github.com/wave-harmonic/crest/assets/114962753/c0a83c16-9686-4345-897f-df37e21aa092

**Comment by daleeidd** [comment]
Thanks. I was able to reproduce. I just needed to move faster.

**Comment by daleeidd** [comment]
Alrighty. I reverted the previous fix made for 4.18 as this introduced reflections at the LOD borders as you saw. Instead I have feathered the dynamic wave inputs to reduce streaking.

LMKWYT. Be aware though there will be some streaking/reflections as it is not possible to eliminate both as far as I can see. What we're looking for is an improvement overall.

**Comment by Revmatek** [comment]
> Alrighty. I reverted the previous fix made for 4.18 as this introduced reflections at the LOD borders as you saw. Instead I have feathered the dynamic wave inputs to reduce streaking.
> 
> LMKWYT. Be aware though there will be some streaking/reflections as it is not possible to eliminate both as far as I can see. What we're looking for is an improvement overall.
> 
> New branch: [fix-dynamic-waves-edge-reflections](https://github.com/wave-harmonic/crest/tree/fix-dynamic-waves-edge-reflections).

I think this looks great! Definitely an overall improvement. I don't see any streaking with normal camera movement / rotating. Corner issue is gone. I did see a very minor streak when impacting the water with a plane (creating a large deformation) and rotating the camera at the same time but I can live with that. I will keep an eye out for similar artifacts in the future and let you know, but this seems good to me.

**Comment by daleeidd** [comment]
Thanks!
